name: 'Build server image'
description: 'Builds the server Docker image and pushes it to GitHub Container Registry'

inputs:
  environment:
    description: 'Environment to deploy to'
    required: true
  commit_sha:
    description: 'Commit SHA to use as image tag'
    required: true
  github_token:
    description: 'GitHub token for registry access'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./packages/server/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/server-${{ inputs.environment }}:latest
          ghcr.io/${{ github.repository }}/server-${{ inputs.environment }}:${{ inputs.commit_sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Clean up registry
      uses: actions/delete-package-versions@v5
      with:
        package-name: project-starter/server-${{ inputs.environment }}
        package-type: container
        min-versions-to-keep: 5

