version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:10.9.0
    environment:
      NODE_ENV: test
    steps:
      - checkout
      - run:
          name: Generate .npmrc
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: Add dependency bin to PATH
          command: export PATH="$PATH:$CIRCLE_WORKING_DIRECTORY/node_modules/.bin"
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages-
      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Lint Project
          command: yarn lint:all
      - run:
          name: Run Tests
          command: yarn test
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_test_results:
          path: test-results.xml

workflows:
  version: 2
  build_test_release:
    jobs:
      - build:
          context: semantic-release
