import { createRouter, RouterProvider } from '@tanstack/react-router';
import ReactDOM from 'react-dom/client';

import './tailwind.css';

import { RouteErrorComponent } from './components/RouteErrorComponent';
// Route tree is code-generated by the tanstack vite plugin
// Actual routes are in the `./routes` directory
import { routeTree } from './routeTree.gen';

const router = createRouter({ routeTree, defaultErrorComponent: RouteErrorComponent });

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}

const rootElement = document.getElementById('root')!;
if (!rootElement.innerHTML) {
  const root = ReactDOM.createRoot(rootElement);
  root.render(<RouterProvider router={router} />);
}
